# Generated by Django 4.2.3 on 2023-08-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('pcId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pcName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userMaster',
            fields=[
                ('userId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('userType', models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('mob', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=30)),
                ('pDesc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('pcId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='orderMaster',
            fields=[
                ('orderId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='orderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('netPrice', models.IntegerField()),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermaster')),
                ('pId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('compId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('compDesc', models.CharField(max_length=1000)),
                ('compDate', models.DateField()),
                ('status', models.CharField(default='Open', max_length=10)),
                ('response', models.CharField(max_length=1000)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
    ]
